name: Auto Accept Quest

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes
    - cron: "1 0 * * *"     # 12:01 AM daily
  workflow_dispatch:        # allows manual triggering

jobs:
  auto-accept-quests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run script
      env:
        HABITICA_USER_ID: ${{ secrets.HABITICA_USER_ID }}
        HABITICA_API_TOKEN: ${{ secrets.HABITICA_API_TOKEN }}
      run: |
        ls -la
        python auto_accept_quests.py

  cast-valorous-presence:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Valorous Presence script
      env:
        HABITICA_USER_ID: ${{ secrets.HABITICA_USER_ID }}
        HABITICA_API_TOKEN: ${{ secrets.HABITICA_API_TOKEN }}
      run: |
        python auto_cast_valorous_presence.py
